CREATE DATABASE Login

CREATE TABLE Users
(
UserID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
UserName VARCHAR(10) NOT NULL,
Password VARCHAR(20) NOT NULL,
RePassword VARCHAR(20) NOT NULL,
Name VARCHAR (20),
Surname VARCHAR(20),
email VARCHAR(100) NOT NULL,
SecretQuestion VARCHAR (210),
SecretAnswer VARCHAR (210),
)
DEFAULT COLLATE utf8_unicode_ci ;
